export const addressCategories = [
  {
    category: 'Residential',
    color: '#4A90E2',
    icon: '🏠',
    types: [
      { label: 'House', icon: '🏠' },
      { label: 'Apartment', icon: '🏢' },
      { label: 'Compound', icon: '🧱' },
      { label: 'Room', icon: '🛏️' },
      { label: 'Bungalow', icon: '🏡' },
      { label: 'Cottage', icon: '🛖' },
      { label: 'Flat', icon: '🛋️' },
      { label: 'Duplex', icon: '🏘️' },
    ],
  },
  {
    category: 'Commercial',
    color: '#F5A623',
    icon: '🏪',
    types: [
      { label: 'Shop', icon: '🏪' },
      { label: 'Office', icon: '🖥️' },
      { label: 'Hotel', icon: '🏨' },
      { label: 'Salon', icon: '💇‍♀️' },
      { label: 'Store', icon: '🛍️' },
      { label: 'Restaurant', icon: '🍽️' },
      { label: 'Kiosk', icon: '🧃' },
      { label: 'Pharmacy', icon: '💊' },
      { label: 'Bar', icon: '🍻' },
    ],
  },
  {
    category: 'Industrial',
    color: '#7F8C8D',
    icon: '🏭',
    types: [
      { label: 'Factory', icon: '🏭' },
      { label: 'Depot', icon: '🚚' },
      { label: 'Warehouse', icon: '📦' },
      { label: 'Workshop', icon: '🔧' },
      { label: 'Mill', icon: '⚙️' },
      { label: 'Plant', icon: '🧪' },
      { label: 'Yard', icon: '🏗️' },
    ],
  },
  {
    category: 'Institutional',
    color: '#27AE60',
    icon: '🏫',
    types: [
      { label: 'School', icon: '🎓' },
      { label: 'Clinic', icon: '🏥' },
      { label: 'Church', icon: '⛪' },
      { label: 'Mosque', icon: '🕌' },
      { label: 'Hospital', icon: '🏥' },
      { label: 'Police', icon: '🚔' },
      { label: 'Embassy', icon: '🏛️' },
    ],
  },
  {
    category: 'OpenLandUtility',
    color: '#8D6E63',
    icon: '🌳',
    types: [
      { label: 'Plot', icon: '📍' },
      { label: 'Farm', icon: '🚜' },
      { label: 'Market', icon: '🛒' },
      { label: 'Garden', icon: '🌼' },
      { label: 'Bridge', icon: '🌉' },
      { label: 'Park', icon: '🌳' },
      { label: 'Site', icon: '🧭' },
      { label: 'Camp', icon: '⛺' },
      { label: 'Garage', icon: '🅿️' },
    ],
  },
];
