import { Colors } from '@/constants';
import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
export const createAddressStyles = StyleSheet.create({
  headerContainer: {
    backgroundColor: Colors.primary[500],
    height: 64,
    paddingHorizontal: 16,
  },
  gentiumText: {
    fontFamily: 'gentium',
  },
  contentContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 0,
  },
  font14: {
    fontSize: 14,
  },
  dialogContentContainer: { paddingTop: 0, paddingBottom: 2 },
  headerText: {
    color: Colors.light[10],
    fontSize: 16,
    fontWeight: '500',
    marginLeft: -36,
  },
  container: {
    flex: 1,
    gap: 4,
  },
  content: {
    flexGrow: 1,
    padding: 20,
    justifyContent: 'flex-start',
    gap: 12,
  },
  inputComponentContainer: {
    position: 'relative',
    backgroundColor: 'white',
    borderRadius: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    paddingTop: 2,
    paddingBottom: 6,
    paddingHorizontal: 20,
    zIndex: 1,
  },
  helpIconContainer: {
    position: 'absolute',
    right: 18,
    top: 8,
  },
  toolTip: {
    position: 'absolute',
    bottom: '110%',
    backgroundColor: 'white',
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 8,
    zIndex: 999,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    width: '100%',
  },
  errorText: {
    marginLeft: 4,
    color: Colors.error,
    fontSize: 12,
  },
  toolTipbottom: {
    width: '100%',
    position: 'absolute',
    top: '110%',
    backgroundColor: 'white',
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 8,
    zIndex: 99,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  tooltipText: {
    fontSize: 12,
    textAlign: 'justify',
  },
  mainInputContainer: {
    height: 40,
    flexDirection: 'row',
    columnGap: 16,
    alignItems: 'center',
  },
  inputContainer: {
    position: 'relative',
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    flexGrow: 1,
    borderBottomColor: Colors['grey-93'],
    overflow: 'hidden',
    flexShrink: 1,
  },
  inputTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputTitle: {
    fontSize: 12,
    color: Colors.primary[500],
    width: '48%',
  },
  fullWidth: {
    width: 'auto',
  },
  input: {
    height: 16,
    backgroundColor: 'transparent',
    borderBottomWidth: 0,
    fontSize: 14,
    overflow: 'hidden',
  },
  dropdownInputHeight: {
    height: 28,
  },
  inputPaddingBottom: {
    paddingBottom: 8,
  },
  textInputContent: {
    paddingLeft: 0,
  },
  optionalText: {
    color: Colors['grey-93'],
  },
  requiredAsterisk: {
    color: Colors.error,
  },
  placeholderText: {
    color: Colors['grey-93'],
    fontSize: 14,
  },
  buttonContainer: {
    position: 'absolute',
    right: 2,
    top: 16,
  },
  rightIcon: {
    width: 24,
    height: 24,
  },
  rightIconContainer: {
    position: 'absolute',
    right: 2,
    top: 8,
  },
  itemText: {
    color: Colors.dark[10],
    fontSize: 14,
  },
  editButton: {
    backgroundColor: Colors.primary[300],
    width: 36,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 2,
  },
  itemContainer: {
    borderBottomWidth: 0.5,
    borderBottomColor: Colors['grey-93'],
  },
  selectedText: {
    fontSize: 12,
  },
  editButtonText: {
    fontSize: 8,
    color: Colors.light[10],
  },
  inputValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 4,
    width: '100%',
  },
  singleInput: {
    flex: 1, // Take the full width when there's only one input
  },
  doubleInput: {
    flex: 0.5, // Each input takes 50% when there are two
  },
  secondInputContainer: {
    flexDirection: 'row',
    columnGap: 4,
    flex: 1,
  },
  dividerText: {
    color: Colors.grey,
  },
  imageContainer: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    rowGap: 16,
    height: 178,
    backgroundColor: Colors.light[10],
    borderRadius: 4,
    borderWidth: 2,
    borderColor: Colors.light[10.5],
    width: '100%',
  },
  image: {
    width: '98%',
    height: 172,
    borderRadius: 2,
  },
  paddingBottom: {
    marginTop: 4,
    rowGap: 6,
    paddingBottom: 0,
  },
  addAPictureContainer: {
    flexDirection: 'row',
    columnGap: 8,
    alignItems: 'center',
  },
  addAPictureText: {
    fontSize: 12,
    color: Colors.primary[500],
  },
  modal: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 160,
    backgroundColor: 'white',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 5,
  },
  modalContent: {
    top: 40,
    height: 132,
    paddingHorizontal: 32,
  },
  uploadOptionsContainer: {
    marginTop: 28,
    rowGap: 12,
  },
  modalTitle: {
    fontSize: 18,
  },
  uploadOption: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 20,
  },
  uploadOptionText: {
    fontSize: 16,
  },
  nodge: {
    width: 40,
    height: 5,
    backgroundColor: '#ccc',
    borderRadius: 3,
    marginTop: 10,
    position: 'absolute',
    top: 10,
    alignSelf: 'center',
  },
  modalText: {
    fontSize: 18,
    marginBottom: 20,
  },
  closeContainer: {
    backgroundColor: Colors.dark[0.5],
    width: 12,
    height: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 8,
    right: 8,
  },
  changeImageContainer: {
    backgroundColor: Colors.dark[0.5],
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingVertical: 2,
    columnGap: 8,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: 8,
    right: 8,
  },
  changeText: {
    fontSize: 10,
    color: Colors.light[10],
  },
  dialogContainer: {
    backgroundColor: Colors.light['10'],
    borderRadius: 8,
    position: 'relative',
    rowGap: 0,
    paddingVertical: 4,
    width: width * 0.94,
    alignSelf: 'center',
    marginHorizontal: 0,
  },
  paddingHorizontal: {
    marginTop: 16,
    paddingLeft: 12,
    paddingRight: 12,
    columnGap: 16,
  },
  dialogSubtitleContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    columnGap: 4,
    paddingHorizontal: 12,
    paddingBottom: 16,
    overflowX: 'hidden',
    flexShrink: 1,
  },
  dialogFirstContent: {
    alignSelf: 'flex-end',
    paddingVertical: 0,
    marginTop: 4,
    marginRight: 4,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 0,
    paddingBottom: 2,
    paddingLeft: 0,
    paddingRight: 4,
  },
  dialogTitle: {
    fontSize: 16,
    color: Colors.primary[500],
    textAlign: 'center',
    fontFamily: 'gentium',
    marginHorizontal: 24,
  },
  dialogSubtitle: {
    textAlign: 'center',
  },
  dialogActionContainer: {
    flexDirection: 'row',
    columnGap: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    paddingBottom: 0,
    overflowX: 'hidden',
  },
  jangoAddress: {
    fontFamily: 'gentium-bold',
    textAlign: 'center',
  },
  addressText: {
    color: Colors.success,
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  addressSuccessfullyCreatedText: {
    color: Colors.success,
    // fontWeight: '500',
    fontFamily: 'gentium-bold',
    textAlign: 'center',
    flexShrink: 1,
  },
  shareAddressButton: {
    borderWidth: 1,
    borderColor: Colors.dark[0.1],
    backgroundColor: Colors.secondary[10],
  },
  shareAddressText: {
    color: Colors.dark[0],
    fontFamily: 'gentium',
  },
});
